### ISSUE TITLE
Add publicPath

### ISSUE THREAD

**Issue by Guru107** [imparvez/react-boilerplate#1]
Add a public path to serve the assets so that all the assets get served from `/assets` route

**Comment by imparvez** [comment]
@Guru107 Can you provide some more details for #1

**Comment by Guru107** [comment]
Search for webpack.js.org for publicPath

**Comment by Guru107** [comment]
In output object the `path` is pointing to just images folder in `dist` and publicPath is pointing to `/images`. Instead of this serve all assets including js,css et. al. from `/assets` and point the path to `dist`
